version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee_app
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - app-network

  migrate:
    image: migrate/migrate
    container_name: employee_migrate
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:12345678@postgres:5432/employee_db?sslmode=disable",
        "up",
      ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: employee_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: employee_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
