env: "local"
http_server:
  address: "localhost:5000"
  timeout: 10s
  idle_timeout: 60s
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "12345678"
  dbname: "employee_db"
  sslmode: "disable"
